/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicWeatherDigestRouteImport } from './routes/api/public/weather-digest'
import { Route as ApiPublicSnapshotUploadRouteImport } from './routes/api/public/snapshot-upload'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedPlantsNewRouteImport } from './routes/_authenticated/plants/new'
import { Route as AuthenticatedPlantsIdRouteImport } from './routes/_authenticated/plants/$id'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSpeciesRouteImport } from './routes/_authenticated/admin/species'
import { Route as AuthenticatedAdminArchiveRouteImport } from './routes/_authenticated/admin/archive'
import { Route as AuthenticatedAdminPlantsIndexRouteImport } from './routes/_authenticated/admin/plants/index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedPlantsIdPhotosRouteImport } from './routes/_authenticated/plants/$id_.photos'
import { Route as AuthenticatedAdminPlantsImportRouteImport } from './routes/_authenticated/admin/plants/import'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicWeatherDigestRoute = ApiPublicWeatherDigestRouteImport.update({
  id: '/api/public/weather-digest',
  path: '/api/public/weather-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotUploadRoute = ApiPublicSnapshotUploadRouteImport.update({
  id: '/api/public/snapshot-upload',
  path: '/api/public/snapshot-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantsNewRoute = AuthenticatedPlantsNewRouteImport.update({
  id: '/plants/new',
  path: '/plants/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantsIdRoute = AuthenticatedPlantsIdRouteImport.update({
  id: '/plants/$id',
  path: '/plants/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSpeciesRoute =
  AuthenticatedAdminSpeciesRouteImport.update({
    id: '/species',
    path: '/species',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminArchiveRoute =
  AuthenticatedAdminArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlantsIndexRoute =
  AuthenticatedAdminPlantsIndexRouteImport.update({
    id: '/plants/',
    path: '/plants/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlantsIdPhotosRoute =
  AuthenticatedPlantsIdPhotosRouteImport.update({
    id: '/plants/$id_/photos',
    path: '/plants/$id/photos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlantsImportRoute =
  AuthenticatedAdminPlantsImportRouteImport.update({
    id: '/plants/import',
    path: '/plants/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/snapshot-upload': typeof ApiPublicSnapshotUploadRoute
  '/api/public/weather-digest': typeof ApiPublicWeatherDigestRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/admin/plants/import': typeof AuthenticatedAdminPlantsImportRoute
  '/plants/$id/photos': typeof AuthenticatedPlantsIdPhotosRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/plants/': typeof AuthenticatedAdminPlantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/snapshot-upload': typeof ApiPublicSnapshotUploadRoute
  '/api/public/weather-digest': typeof ApiPublicWeatherDigestRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/admin/plants/import': typeof AuthenticatedAdminPlantsImportRoute
  '/plants/$id/photos': typeof AuthenticatedPlantsIdPhotosRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/plants': typeof AuthenticatedAdminPlantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/_authenticated/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/_authenticated/plants/new': typeof AuthenticatedPlantsNewRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/snapshot-upload': typeof ApiPublicSnapshotUploadRoute
  '/api/public/weather-digest': typeof ApiPublicWeatherDigestRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/admin/plants/import': typeof AuthenticatedAdminPlantsImportRoute
  '/_authenticated/plants/$id_/photos': typeof AuthenticatedPlantsIdPhotosRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/plants/': typeof AuthenticatedAdminPlantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/feed'
    | '/friends'
    | '/settings'
    | '/admin/archive'
    | '/admin/species'
    | '/admin/users'
    | '/messages/$id'
    | '/plants/$id'
    | '/plants/new'
    | '/u/$username'
    | '/api/public/ingest'
    | '/api/public/snapshot-upload'
    | '/api/public/weather-digest'
    | '/admin/'
    | '/messages/'
    | '/admin/plants/import'
    | '/plants/$id/photos'
    | '/lovable/email/transactional/preview'
    | '/admin/plants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/feed'
    | '/friends'
    | '/settings'
    | '/admin/archive'
    | '/admin/species'
    | '/admin/users'
    | '/messages/$id'
    | '/plants/$id'
    | '/plants/new'
    | '/u/$username'
    | '/api/public/ingest'
    | '/api/public/snapshot-upload'
    | '/api/public/weather-digest'
    | '/admin'
    | '/messages'
    | '/admin/plants/import'
    | '/plants/$id/photos'
    | '/lovable/email/transactional/preview'
    | '/admin/plants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/friends'
    | '/_authenticated/settings'
    | '/_authenticated/admin/archive'
    | '/_authenticated/admin/species'
    | '/_authenticated/admin/users'
    | '/_authenticated/messages/$id'
    | '/_authenticated/plants/$id'
    | '/_authenticated/plants/new'
    | '/_authenticated/u/$username'
    | '/api/public/ingest'
    | '/api/public/snapshot-upload'
    | '/api/public/weather-digest'
    | '/_authenticated/admin/'
    | '/_authenticated/messages/'
    | '/_authenticated/admin/plants/import'
    | '/_authenticated/plants/$id_/photos'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/plants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicSnapshotUploadRoute: typeof ApiPublicSnapshotUploadRoute
  ApiPublicWeatherDigestRoute: typeof ApiPublicWeatherDigestRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/weather-digest': {
      id: '/api/public/weather-digest'
      path: '/api/public/weather-digest'
      fullPath: '/api/public/weather-digest'
      preLoaderRoute: typeof ApiPublicWeatherDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snapshot-upload': {
      id: '/api/public/snapshot-upload'
      path: '/api/public/snapshot-upload'
      fullPath: '/api/public/snapshot-upload'
      preLoaderRoute: typeof ApiPublicSnapshotUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/new': {
      id: '/_authenticated/plants/new'
      path: '/plants/new'
      fullPath: '/plants/new'
      preLoaderRoute: typeof AuthenticatedPlantsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/$id': {
      id: '/_authenticated/plants/$id'
      path: '/plants/$id'
      fullPath: '/plants/$id'
      preLoaderRoute: typeof AuthenticatedPlantsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/species': {
      id: '/_authenticated/admin/species'
      path: '/species'
      fullPath: '/admin/species'
      preLoaderRoute: typeof AuthenticatedAdminSpeciesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/archive': {
      id: '/_authenticated/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AuthenticatedAdminArchiveRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plants/': {
      id: '/_authenticated/admin/plants/'
      path: '/plants'
      fullPath: '/admin/plants/'
      preLoaderRoute: typeof AuthenticatedAdminPlantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plants/$id_/photos': {
      id: '/_authenticated/plants/$id_/photos'
      path: '/plants/$id/photos'
      fullPath: '/plants/$id/photos'
      preLoaderRoute: typeof AuthenticatedPlantsIdPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/plants/import': {
      id: '/_authenticated/admin/plants/import'
      path: '/plants/import'
      fullPath: '/admin/plants/import'
      preLoaderRoute: typeof AuthenticatedAdminPlantsImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminArchiveRoute: typeof AuthenticatedAdminArchiveRoute
  AuthenticatedAdminSpeciesRoute: typeof AuthenticatedAdminSpeciesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPlantsImportRoute: typeof AuthenticatedAdminPlantsImportRoute
  AuthenticatedAdminPlantsIndexRoute: typeof AuthenticatedAdminPlantsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminArchiveRoute: AuthenticatedAdminArchiveRoute,
    AuthenticatedAdminSpeciesRoute: AuthenticatedAdminSpeciesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPlantsImportRoute: AuthenticatedAdminPlantsImportRoute,
    AuthenticatedAdminPlantsIndexRoute: AuthenticatedAdminPlantsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedPlantsIdRoute: typeof AuthenticatedPlantsIdRoute
  AuthenticatedPlantsNewRoute: typeof AuthenticatedPlantsNewRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedPlantsIdPhotosRoute: typeof AuthenticatedPlantsIdPhotosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedPlantsIdRoute: AuthenticatedPlantsIdRoute,
  AuthenticatedPlantsNewRoute: AuthenticatedPlantsNewRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedPlantsIdPhotosRoute: AuthenticatedPlantsIdPhotosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicSnapshotUploadRoute: ApiPublicSnapshotUploadRoute,
  ApiPublicWeatherDigestRoute: ApiPublicWeatherDigestRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
